apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels: 
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: mmravi99/helloworld:latest
        resources:
          limits:
            cpu: '1'
            memory: '1G'
          requests:
            cpu: '1'
            memory: '1G'
        ports:
        - name: vproapp-port
          containerPort: 8080
