 apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: petclicnic-hpa
spec:
 maxReplicas: 5
 minReplicas: 1
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: vproapp
 targetCPUUtilizationPercentage: 50
